# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-22 19:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='location',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='organization',
            name='name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='organization',
            name='website',
            field=models.URLField(default='', verbose_name='URL'),
        ),
    ]
