# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-24 07:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0002_auto_20170822_1915'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='Description',
            field=models.CharField(default='', max_length=200),
        ),
    ]
